// Generated by CoffeeScript 1.10.0
// 这个必须最后执行
// 在qq 目录下面 npm install redis
//  eg.	study 你个傻逼 echo '你才是'
//  eg.	study 你瞅啥 echo '瞅你咋地'
//  eg.	study 再瞅你试试 echo '四四一十六'

(function() {
  var redis   = require('redis');
  var process = require('child_process');

  /*
   @param content 消息内容
   @param send(content)  回复消息
   @param robot qqbot instance
   @param message 原消息对象
   */

  module.exports = function(content, send, robot, message) {
    
	if (content.match(/^study\s+(.*)$/i)) {
	  var client  = redis.createClient('6379', '127.0.0.1');
	  
      
	  client.select('15', function(error){
		if(error) {
			send('err:'+error);
		} else {
			// set
			var array = content.split(/\s+/);
			var key1 = array[1];
			var value1 = array.splice(2).join(' ')
			  console.log('key='+key1+',value='+value1)
			  client.set(key1, value1, function(error, res) {
				if(error) {
					send('err:'+error);
				} else {
					send(res);
				}
				// 关闭链接
				client.end();
			});
		}
	});
    }
	// 这个必须最后执行
	if (content.match(/^(.+)$/i)) {
	  var client  = redis.createClient('6379', '127.0.0.1');
	  
      var key = content;
		client.select('15', function(error){
		if(error) {
			send('err:'+error);
		} else {
			// get
			client.get(key, function(error, value){
				if(error) {
					console.log('err:'+error);
				} else {
					  if(value){
						  console.log(value);
						  cmd=value;
						  process.exec(cmd,function(err,stdout,stderr){
								if(err){
									send(stderr);
								}else{
									send(stdout);
								}
						  });
					  }else{
						send("不知道 "+key+" 啥意思，试试study教教我。")
					  }
					  
				}
				// 关闭链接
				client.end();
			});
		}
		});
    }
  };

}).call(this);