// Generated by CoffeeScript 1.10.0

(function() {

  var HELP_INFO = "list   #显示支持的主机\ntop #显示当前主机信息\ncmd ip/user@ip 命令            #执行命令\ntop ip/user@ip         #显示指定ip主机信息\nstudy key value            #学习相关于命令映射\n其余语句按学习后的指令来处理\nremember            #显示记忆的key名称\nremember key           #显示记忆key具体信息 (key + value)\nforget key           #删除记忆的key\n另外,现在为了防止由于qq消息过长导致消息发送失败，返回消息超过50字符的部分将用...代替";

  var fs = require('fs');

  var Path = require('path');
  
  var proc = require('child_process');
  
  var util = require(__dirname+'/../lib/util.js');
  
 
  /*
   @param content 消息内容
   @param send(content)  回复消息
   @param robot qqbot instance
   @param message 原消息对象
   */

  module.exports = function(content, send, robot, message) {
	  
	//console.log(util)
	
	  
	content = util.formatContent(content,message);
	if(!content){
		return;
	}
	
    if (content.match(/^help$/i)) {
      send(HELP_INFO);
    }
    if (content.match(/^list$/i)) {
      send("192.168.200.216\n192.168.200.215");
    }
	if (content.match(/^top$/i)) {
	   var cmd="sh "+__dirname+"/../lib/top.sh"
	   proc.exec(cmd,function(err,stdout,stderr){
			if(err){
				send(stderr);
			}else{
				send(stdout);
			}
	   });
    }
	if (content.match(/^top\s+(.*)$/i)) {
      var array = content.split(/\s+/);
      var ip = array[1];
	  var sshcmd="ssh "+ip+" sh <"+__dirname+"/../lib/top.sh "
	  console.log(sshcmd);
	  proc.exec(sshcmd,function(err,stdout,stderr){
			if(err){
				send("执行主机:"+ip+ "\n"+stderr);
			}else{
				send("执行主机:"+ip+ "\n"+stdout);
			}
	  });
    }
	if (content.match(/^cmd\s+(.*)$/i)) {
      var array = content.split(/\s+/);
      var ip = array[1];
	  var cmd = array.splice(2).join(' ')
	  var sshcmd="ssh "+ip+" "+cmd;
	  console.log(sshcmd);
	  proc.exec(sshcmd,function(err,stdout,stderr){
			if(err){
				send(stderr);
			}else{
				send(util.maxLength(stdout));
			}
	  });
    }
  };

}).call(this);